version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgres://yourusername:yourpassword@db:5432/nitro

  db:
    image: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: nitro
    ports:
      - '5432:5432'
