services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/robot_cleaner
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=robot_cleaner
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
